name: book-reader-chatbot
services:
  - name: web
    type: web
    source:
      git:
        repository: your-github-username/Book_reader_chatbot
        branch: main
    env:
      - name: GEMINI_API_KEY
        value: your_gemini_api_key_here
      - name: FLASK_ENV
        value: production
      - name: FLASK_DEBUG
        value: false
      - name: PORT
        value: 8080
      - name: PYTHON_VERSION
        value: "3.9.18"
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: NUMBA_CACHE_DIR
        value: "/tmp"
    ports:
      - port: 8080
        protocol: http
    routes:
      - path: /
        protocol: http
    healthcheck:
      http:
        path: /health
        port: 8080
      initial_delay: 45s
      interval: 15s
      timeout: 10s
      unhealthy_threshold: 3
    resources:
      cpu: 0.25
      memory: 512Mi
    scaling:
      min: 1
      max: 1
    build:
      requirements: requirements-koyeb.txt
      build_command: |
        pip install --no-cache-dir -r requirements-koyeb.txt
        pip install --no-cache-dir numpy==1.24.3
